run:
  timeout: 5m
  skip-dirs:
    - vendor
linters:
  disable-all: true
  enable:
    - gofmt
    - golint
    - goimports
  fast: false
linters-settings:
  gofmt:
    simplify: false
  gci:
    local-prefixes: github.com/ameykpatil/chatbot
issues:
  exclude-use-default: false